// <auto-generated />
using HealthMonitor.DataAccesLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HealthMonitor.DataAccesLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260401103436_CreateDeleteAPI")]
    partial class CreateDeleteAPI
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HealthMonitor.Domain.Entities.Food.FoodEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<float>("calories")
                        .HasColumnType("real");

                    b.Property<float>("carbohydrates")
                        .HasColumnType("real");

                    b.Property<float>("fat")
                        .HasColumnType("real");

                    b.Property<float>("fiber")
                        .HasColumnType("real");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("protein")
                        .HasColumnType("real");

                    b.Property<float>("vitaminC")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.ToTable("Foods");
                });
#pragma warning restore 612, 618
        }
    }
}
